#!/bin/bash

TERM_LIST=${1:-2:antiX-blue-purple 3:antiX-rev-neutral 4:antiX-purple 5:antiX-rev-blue 6:antiX-neutral-purple}

[ $# -gt 0 ] && shift

[ -e /sys/class/graphics/fb0/virtual_size ] || exit 0

for term_theme in $TERM_LIST $*; do
    term=$(echo $term_theme  | cut -d: -f1)
    theme=$(echo $term_theme | cut -d: -f2)
    splash-term $term $theme &>> /var/log/splash-all.log
done

exit 0
