#!/bin/sh

### BEGIN INIT INFO
# Provides:          live-static-persist
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description:
# Description:       delete files from rootfs when static persist
### END INIT INFO


LIST_FILE=/usr/local/share/excludes/static-root-delete.list

main() {
    case $1 in
        start)                               ;;
         stop) delete_static_rootfs          ;;
            *) echo "Usage: $0 {start|stop}" ;;
    esac
    exit 0
}

delete_static_rootfs() {
    test -e /live/config/static-rootfs || exit 0
    . /live/lib/live-init-utils.sh
    #load_translation
    echo_script "deleting some static rootfs files" $0
    echo rm -rf $(grep -v "^\s*#" $LIST_FILE | sed -r -e 's/\s+#.*//' | grep "/[a-zA-Z0-9]")
}

main "$@"



