#!/bin/sh

### BEGIN INIT INFO
# Provides:          live-usb-save
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:       save/restore some information on raw liveusb w/o persistence
### END INIT INFO

. /live/lib/live-init-utils.sh

start_init_logging
load_translation

main() {
    case $1 in
        start) restore_desktop               ;;
         stop) save_desktop                  ;;
            *) echo "Usage: $0 {start|stop}" ;;
    esac
    exit 0
}

save_desktop() {
    get_init_param REMASTERABLE
    [ "$REMASTERABLE" ] || return

    get_init_param DID_TORAM
    if [ "$DID_TORAM" ]; then

        get_init_param BOOT_UUID
        if [ -z "$BOOT_UUID" ; then
            echo_live "$_Could_not_find_UUID_of_boot_device_for_remounting_"
            echo_live "$_Will_not_save_default_desktops_"
            return
        fi

        mkdir -p /live/boot-dev/
        if ! mount -U $BOOT_UUID /live/boot-dev; then
            echo_live "$_Could_not_remount_boot_device_"
            echo_live "$_Will_not_save_default_desktops_"
            return
        fi
    fi

    get_init_param SQFILE_PATH
    local to_dir=/live/boot-dev/$SQFILE_PATH/personalize/by-user

    local user from to
    for user in $(ls /home); do
        from="/home/$user/.desktop-session/default-desktop"
        [ -e "$from" ] || continue
        to="$to_dir/$user/default-desktop"
        should_copy "$from" "$to" || continue
        mkdir -p $(dirname "$to")
        echo_live "$_Save_X_desktop_Y_" $(pquote $user) $(pquote $(cat $from))
        cp "$from" "$to"
    done
}

restore_desktop() {
    # There are many reasons to not restore
    [ "$CMD_DESKTOP" ] && return

    get_init_param REMASTERABLE
    [ "$REMASTERABLE" ] || return

    get_init_param PERSISTENCE
    [ "$PERSISTENCE" ] && return

    get_init_param SQFILE_PATH

    local d from_dir
    for d in /live/boot-dev live/to-ram; do
        d=$d/$SQFILE_PATH/personalize/by-user
        [ -d $d ] || continue
        from_dir=$d
        break
    done

    [ "$from_dir" ] || return

    local user dest_dir dest sorc
    for user in $(ls $from_dir); do
        sorc=$from_dir/$user/default-desktop
        dest_dir=/home/$user/.desktop-session
        [ -d "$dest_dir" ] || continue
        [ -e "$sorc"     ] || continue
        local dest=$dest_dir/default-desktop
        should_copy $sorc $dest || continue
        echo_live "$_restore_X_desktop_to_Y_" $(pquote $user) $(pquote $(cat $sorc))
        cp "$sorc" "$dest"
        chown $user:users $dest
    done
}

should_copy() {
    local from="$1"  to="$2"
    [ -e "$from" ] || return 1
    [ -e "$to"   ] || return 0
    diff -q "$from" "$to" 1>/dev/null 2>/dev/null && return 1
    return 0
}

main "$@"

