#!/bin/sh

### BEGIN INIT INFO
# Provides:          persist-autosave
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:       Run persist-config on startup if needed.  Run persist-save if needed
### END INIT INFO

# . /usr/share/antiX/lib/live-init-utils.sh
. /live/lib/live-init-utils.sh

start_init_logging
load_translation
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/live/bin

main() {
    case $1 in
        start) do_start                      ;;
         stop) do_stop                       ;;
            *) echo "Usage: $0 {start|stop}"
               exit 1                        ;;
    esac
    exit 0
}


do_start() {
    local persist_conf=/etc/live/config/persist-config.conf
    local new_passwd=/live/config/new-passwords

    # Bail early if no persist-config is needed
    if [ -e $persist_conf ]; then
        # But still do a persist-save if there are new passwords
        [ -e $new_passwd ] || exit 0
        echo "Saving new passwords in persistence file"
        persist-save --quiet -cli --nolog
        exit 0
    fi

    persist-config --cli --startup --nolog
    [ -e $persist_conf -o -e $new_passwd ] || exit 0
    [ -e $new_passwd ]   && echo "Save new passwords"
    [ -e $persist_conf ] && echo "Save new autosave selection"

    persist-save --quiet -cli --nolog
}

do_stop() {

    # bail early
    [ -e /live/config/save-persist ] || return
    echo_script "$_Possibly_save_persistent_information_" $0

    # Don't auto-save twice in a row
    local last_save_file=/live/config/last-auto-save
    if test -r $last_save_file; then
        local prev=$(cat $last_save_file)
        local diff=$(( $(date +%s) - $(cat $last_save_file)))
        if [ $diff -le 10 ]; then
            echo_live "$_Already_autosaved_X_seconds_ago_" $diff
            echo_live "$_Wont_autosave_again_"
            return
        fi
    fi

    local p_config=/usr/local/bin/persist-config
    test -x $p_config && $p_config --cli --shutdown
}

main "$@" 2>&1 | tee -a $INIT_LOG_FILE

